minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.19.3

#Fabric api
fabric_version=0.119.4+1.21.4
fabric_versiononly=0.119.4

modmenu_version=13.0.3

gbfabrictools_version=1.4+1.20
